[package]
name = "gem5_conv"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "=4.5.23", features = ["derive"] }
flate2 = "1.0.35"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
